Repository vuejs-translations/docs-it, pull requests merged in 2023-10, with the labels that each got.

#123 26 apisfc
  src/api/sfc-css-features.md
  src/api/sfc-script-setup.md
  src/api/sfc-spec.md
Labels: miglioramento

#110 20 guideextras
  src/guide/extras/animation.md
  src/guide/extras/demos/Colors.vue
  src/guide/extras/demos/DisabledButton.vue
  src/guide/extras/demos/ElasticHeader.vue
  src/guide/extras/demos/spreadSheetStore.js
  src/guide/extras/ways-of-using-vue.md
Labels: traduzione in corso, necessaria revisione, revisione in corso

#157 fix: #156 - Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: necessaria revisione, revisione in corso

#151 reactivity-in-depth translated
  src/guide/extras/reactivity-in-depth.md
Labels: revisione in corso

#155 docs: partners/components (#31)
  src/partners/components/PartnerAll.vue
  src/partners/components/PartnerCard.vue
  src/partners/components/PartnerHero.vue
  src/partners/components/PartnerJoin.vue
  src/partners/components/PartnerLanding.vue
  src/partners/components/PartnerList.vue
  src/partners/components/PartnerPage.vue
Labels: revisione in corso, necessarie modifiche
